---
- include: ntc_show/sh_access_list.yml

- set_fact:
    running_acl: "{{ show_access_list.response|selectattr('name', 'match', 'nat_net')|map(attribute='sn')|list }}"

- set_fact:
    vars_acl: "{{ nat_net|map(attribute='seq_no')|list }}"

- set_fact:
    diff: "{{ running_acl|difference(vars_acl) }}"

- name: network address translation configs
  ios_config:
    src: nat.j2
