---
- name: interfaces config snippet
  hosts: all
  gather_facts: no
  connection: local
  serial: 1

  tasks:
  - include_role:
      name: interfaces
      tasks_from: svi.yml
    tags: svi

  - include_role:
      name: interfaces
      tasks_from: loopback.yml
    tags: loop

  - include_vars: vars/networks.yml
    tags: layer3

  - include_role:
      name: interfaces
      tasks_from: layer3.yml
    tags: layer3
