---
- name: routing config snippet
  hosts: dist-sw,wan-router
  gather_facts: no
  connection: local
  serial: 1

  tasks:
  - include_role:
      name: interfaces
      tasks_from: svi.yml
    tags: svi
    when: svi_id is defined

  - include_role:
      name: interfaces
      tasks_from: loopback.yml
    tags: loop
    when: loop_id is defined

  - include_role:
      name: interfaces
      tasks_from: layer3.yml
    tags: layer3
    when: interfaces is defined

  - include_role:
      name: routing
      tasks_from: facts.yml
    tags: ['svi', 'loop', 'layer3', 'eigrp']

  - include_role:
      name: routing
      tasks_from: eigrp.yml
    tags: ['svi', 'loop', 'layer3', 'eigrp']
