---
- name: ip-services config snippet
  hosts: layer3dev
  gather_facts: no
  connection: local
  serial: 1

  tasks:
  - include_role:
      name: ip-services
      tasks_from: glbp.yml
    tags: glbp
    when: glbp is defined

  - include_role:
      name: ip-services
      tasks_from: nat.yml
    tags: nat
    when: nat is defined
