---
- name: ip-services config snippet
  hosts: all
  gather_facts: no
  connection: local
  serial: 1

  tasks:

  - include_role:
      name: ip-services
      tasks_from: glbp.yml
    tags: glbp

  - include_role:
      name: ip-services
      tasks_from: acl.yml
    tags: acl

  - include_role:
      name: ip-services
      tasks_from: nat.yml
    tags: nat
