---
- name: lan-switching config snippet
  hosts: acc-sw,dist-sw
  gather_facts: no
  connection: local
  serial: 1

  tasks:

  - include: gather_facts/vlan.yml
    tags: ['vlan', 'access', 'trunk']

  - include_role:
      name: roles/lan-switching
      tasks_from: vlan.yml
    tags: vlan

  - include_role:
      name: roles/lan-switching
      tasks_from: access.yml
    tags: access

  - include_role:
      name: roles/lan-switching
      tasks_from: stp.yml
    tags: stp

  - include_role:
      name: roles/lan-switching
      tasks_from: trunk.yml
    tags: trunk
