---
- name: lan-switching config snippet
  hosts: acc-sw,dist-sw
  gather_facts: no
  connection: local
  serial: 1

  tasks:
  - include_role:
      name: lan-switching
      tasks_from: facts.yml
    tags: ['vlan', 'access', 'trunk']

  - include_role:
      name: lan-switching
      tasks_from: vlan.yml
    tags: vlan

  - include_role:
      name: lan-switching
      tasks_from: access.yml
    tags: access
    when: access_ports is defined

  - include_role:
      name: lan-switching
      tasks_from: stp.yml
    tags: stp

  - include_role:
      name: lan-switching
      tasks_from: trunk.yml
    tags: trunk
    when: access_ports is defined
