---
- name: access switch
  hosts: acc-sw
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - { role: lan-switching, tags: lan }

- name: distribution switch
  hosts: dist-sw
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - { role: lan-switching, tags: lan }
    - { role: interfaces, tags: int }
    - { role: ip-services, tags: ip }
    - { role: routing, tags: routing }

- name: routers
  hosts: wan-router
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - { role: interfaces, tags: int }
    - { role: ip-services, tags: ip }
    - { role: routing, tags: routing }
