---
- name: interfaces config snippet
  hosts: all
  gather_facts: no
  connection: local
  serial: 1

  tasks:

  - include_role:
      name: roles/interfaces
      tasks_from: tasks/svi.yml
    tags: svi

  - include_role:
      name: roles/interfaces
      tasks_from: tasks/loopback.yml
    tags: loop

  - include_role:
      name: roles/interfaces
      tasks_from: tasks/layer3.yml
    tags: layer3
