---
- name: access switch
  hosts: acc-sw
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - { role: switchports, tags: access-trunk }

- name: distribution switch
  hosts: dist-sw
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - { role: switchports, tags: access-trunk }
    - { role: glbp, tags: glbp }
    - { role: eigrp, tags: eigrp }

- name: routers switch play
  hosts: wan-router
  gather_facts: no
  connection: local
  serial: 1
  roles:
    - { role: eigrp, tags: eigrp }
