---
- name: access ports configs
  hosts: acc-sw
  gather_facts: no
  connection: local

  tasks:

  - include_role:
      name: vlan

  - set_fact:
      var_vlan_list: "{{ vlans|map(attribute='id')|list }}"

  - include_role:
      name: switchports
      tasks_from: access.yml
