---
- name: routing protocol configuration
  hosts: dist-sw,wan-router
  gather_facts: no
  connection: local

  tasks:

  - include_role:
      name: interfaces
      tasks_from: svi.yml
    tags: svi

  - include_role:
      name: interfaces
      tasks_from: loopback.yml
    tags: loop

  - include_role:
      name: interfaces
      tasks_from: layer3.yml
    tags: layer3

  - include: set_fact/interface_facts.yml
    tags: ['svi', 'loop', 'layer3', 'eigrp']

  - include_role:
      name: routing-protocol
      tasks_from: eigrp.yml
    tags: ['svi', 'loop', 'layer3', 'eigrp']
