---
- name: create vlans
  ios_config:
    src: add_vlan.j2

- include: vlan_facts.yml

- name: remove VLAN/s
  ios_config:
    src: remove_vlan.j2

- include: svi_facts.yml
  when: svi_id is defined

- name: remove SVI/s
  ios_config:
    src: remove_svi.j2
  when: svi_id is defined
