---
- name: fail if data VLAN not exist in vlan_01
  fail: msg="no data VLAN {{ item.data }} found on {{ ansible_hostname }} vlan_01 variable"
  with_items: "{{ access_ports }}"
  when: item.data|string not in vars_vlan_id

- name: fail if voice VLAN not exist in vlan_01
  fail: msg="no voice VLAN {{ item.voice }} found on [{{ ansible_hostname }}] vlan_01 variable"
  with_items: "{{ access_ports }}"
  when: item.voice is defined and item.voice|string not in vars_vlan_id

- name: access port configs
  ios_config:
    src: access-ports.j2

- name: wait for access port-channel/s to come up
  ios_command:
    commands: show interfaces port-channel {{ item.group }}
    wait_for: result[0] contains 'line protocol is up'
  with_items: "{{ access_ports }}"
  when: item.group is defined

- name: access port-channel configs
  ios_config:
    src: access-port-channel.j2
