---
- include: ntc_show/sh_vlan.yml

- name: list of active VLAN
  set_fact:
    active_vlan_id: "{{ show_vlan.response|map(attribute='vlan_id')|reject('match', '1001')|reject('match', '1002')|reject('match', '1003')|reject('match', '1004')|reject('match', '1004')|reject('match', '1005')|list }}"

- name: list of variable VLAN
  set_fact:
    vars_vlan_id: "{{ vlans|map(attribute='id')|list }}"
