---
- name: ip-services config snippet
  hosts: dist-sw,wan-router
  gather_facts: no
  connection: local

  tasks:

  - include_role:
      name: roles/interfaces
      tasks_from: tasks/svi.yml
    tags: svi

  - include_role:
      name: roles/ip-services
      tasks_from: tasks/glbp.yml
    tags: ['svi', 'glbp']
