---
- name: ip-services config snippet
  hosts: dist-sw,wan-router
  gather_facts: no
  connection: local
  serial: 1

  tasks:

  - include_role:
      name: roles/ip-services
      tasks_from: tasks/glbp.yml
    tags: glbp

    - include_role:
        name: roles/ip-services
        tasks_from: tasks/acl.yml
      tags: acl

    - include_role:
        name: roles/ip-services
        tasks_from: tasks/nat.yml
      tags: nat
