---
vlan_01:
  - { id: '10', name: voice-10 }
  - { id: '100', name: data-100 }
  - { id: '20', name: voice-20 }
  - { id: '120', name: data-120 }
  - { id: '121', name: data-121 }

vlans: "{{ vlan_01 + vlan_02 }}"

# Specify a range of ports to be trunk or access.
# If you wanted to implement port-channel, just add the 'group' attribute
# in the list of dictionaries.
access_ports:
  - { ports: ['Et1/0 - 3'], voice: 10, data: 100 }
  - { ports: ['Et2/0 - 3'], voice: 20, data: 120 }

trunk_ports:
  - { ports: ['Et0/0 - 1'], group: 1 }
  - { ports: ['Et0/2 - 3'], group: 2 }

allowed_vlans: "{{ vlans|map(attribute='id')|list|join(',') }}"
