---
loop_id: 11

interfaces: # - { interface: , host: , net: "{{ tem.net }}", mask: "{{ tem.mask }}" }
  - { interface: 'Et0/0', host: 2, net: "{{ ma_01.net }}", mask: "{{ ma_01.mask }}", sum_add: '0.0.0.0/0', ip_nat: inside, ip_acc: nat-network }
  - { interface: 'Et1/0', ip_nat: outside, dhcp: yes }
