---
- include: check_vlan.yml

- name: access port configs
  ios_config:
    src: access-ports.j2

- name: wait for port-channel/s to come up
  ios_command:
    commands: show interfaces port-channel {{ item.group }}
    wait_for: result[0] contains 'line protocol is up'
  with_items: "{{ access_ports }}"
  when: item.group is defined

- name: port-channel configs
  ios_config:
    src: port-channel.j2
